class_name MapGenConfig
extends RefCounted

@export var map_size: Vector2i = Vector2i(64, 64)
@export var ridge_width: int = 5
@export var noise_strength: float = 0.13
@export var peak_threshold: float = 0.92
@export var mountain_threshold: float = 0.76
@export var hill_threshold: float = 0.53
@export var ridge_branch_min: int = 0
@export var ridge_branch_max: int = 1
@export var ridge_edge_margin: int = 2
@export var ridge_control_point_jitter: int = 5
@export var mountain_height_sample_step: int = 0
@export var height_noise_frequency: float = 0.085
@export var moisture_noise_frequency: float = 0.07
@export var spawn_edge_margin: int = 3
@export var spawn_open_radius: int = 2
@export var spawn_open_min_cells: int = 10
@export var challenge_count: int = 1
@export var chest_count: int = 1
@export var ruin_count: int = 1
@export var easter_egg_count: int = 1
@export var enemy_count: int = 4
@export var enemy_min_distance_from_spawn: int = 8
@export var secondary_region_min_cells: int = 6
@export var extra_region_connection_budget: int = 5
@export var bonus_shortcut_passes: int = 3
@export var shortcut_min_blocked_cells: int = 5
@export var pass_width_min: int = 3
@export var pass_width_max: int = 5
@export var pass_widen_chance: float = 0.60
@export var local_gap_region_max_cells: int = 24
@export var local_gap_max_distance: int = 6
@export var forest_blocker_density_min: float = 0.14
@export var forest_blocker_density_max: float = 0.20
@export var forest_blocker_cluster_min_size: int = 1
@export var forest_blocker_cluster_max_size: int = 6
@export var forest_blocker_cluster_radius: int = 2
@export var forest_blocker_max_local_density: int = 4
@export var spawn_clear_radius: int = 2
@export var tavern_clear_radius: int = 2
@export var tavern_count: int = 0
@export var challenge_clear_radius: int = 1
@export var poi_clear_radius: int = 1
@export var shrine_count: int = 1
@export var use_fast_noise_lite: bool = true
@export var allow_fast_noise_lite_stub: bool = true
